"""Added several foreign key indixes

Revision ID: 26ef06c2773
Revises: 2969375b278
Create Date: 2014-05-06 16:10:39.467216

"""

# revision identifiers, used by Alembic.
revision = '26ef06c2773'
down_revision = '2969375b278'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_album_artist_id', 'album', ['artist_id'])
    op.create_index('ix_lastfm_track_info_track_id', 'lastfm_track_info',
                    ['track_id'])
    op.create_index('ix_scrobble_scrobble_info_id', 'scrobble',
                    ['scrobble_info_id'])
    op.create_index('ix_scrobble_track_id', 'scrobble', ['track_id'])
    op.create_index('ix_track_album_id', 'track', ['album_id'])
    op.create_index('ix_track_artist_id', 'track', ['artist_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_album_artist_id')
    op.drop_index('ix_lastfm_track_info_track_id')
    op.drop_index('ix_scrobble_scrobble_info_id')
    op.drop_index('ix_scrobble_track_id')
    op.drop_index('ix_track_album_id')
    op.drop_index('ix_track_artist_id')
    ### end Alembic commands ###
