"""Add is_duplicate column to track

Revision ID: 2969375b278
Revises: None
Create Date: 2013-09-26 15:37:01.898005

"""

# revision identifiers, used by Alembic.
revision = '2969375b278'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track', sa.Column('is_duplicate', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'is_duplicate')
    ### end Alembic commands ###
