"""Added index for track fiename

Revision ID: 5807c663b37
Revises: 26ef06c2773
Create Date: 2014-05-06 22:40:38.864923

"""

# revision identifiers, used by Alembic.
revision = '5807c663b37'
down_revision = '26ef06c2773'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_track_filename', 'track', ['filename'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_track_filename')
    ### end Alembic commands ###
