language: python

env:
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34

install:
  - pip install tox
  - pip install .
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

python:
  - "3.4"

script:
  - tox
